version: '3.8'

services:
  telegram-bot:
    image: telegram-bot
    build: .
    container_name: telegram-bot
    restart: always
    environment:
      - TELEGRAM_API_TOKEN=${TELEGRAM_API_TOKEN}
    ports:
      - "3000:8080"
