name: Go App with Docker & SSH

on:
  push:
    branches:
    - master
  pull_request:


jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Construir a imagem Docker
      run: docker build -t telegram-bot .

    - name: Rodar o container
      run: |
        docker run -d --name go-container -p 8080:3000 telegram-bot
        sleep 5  # Aguarde a inicialização

    - name: Testar aplicação Go
      run: curl -s http://localhost:3000
