name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    env:
        APP_ENV: production
        TELEGRAM_API_TOKEN: ${{ secrets.TELEGRAM_API_TOKEN }}  
    runs-on: self-hosted
   
    steps:
    - uses: actions/checkout@v4
    - name: Construir a imagem Docker
      run: docker build -t telegram-bot .

    - name: Apagar lixo step 1
      continue-on-error: true
      run: docker stop telegram-bot 

    - name: Apagar lixo step 2
      continue-on-error: true
      run: docker rm telegram-bot 

    - name: Rodar o container
      run: 
        docker run -d --name telegram-bot -p 3000:8080 telegram-bot

    - name: Testar aplicação Go
      run: curl -s http://localhost:3000/health

  