name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Construir a imagem Docker
      run: docker build -t telegram-bot .

    - name: Rodar o container
      run: |
        docker run -d --name go-container -p 8080:3000 telegram-bot
        sleep 5  # Aguarde a inicialização

    - name: Testar aplicação Go
      run: curl -s http://localhost:8080/health