name: Hello World

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  workflow_dispatch:


jobs:
  hello-world:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Print Hello World
      run: echo "Hello, World!"
